// GENERATED by scripts/gen-rules.py from the moderation bot's db/rules_content.py. Don't edit by hand:
// change the bot file, run the script, and run /rules refresh in Discord so both stay the same.
// Text uses **bold** and [links](url).

export type Rule = { n: number; title: string; points: string[]; bad: string[]; good: string[] };
export type RulePart = { key: string; title: string; label: string; emoji: string; color: string; intro: string; rules: Rule[]; info: { title: string; body: string }[] };

export const RULES: { intro: string; tldr: string[]; parts: RulePart[] } = {
  "intro": "Welcome to Kitty Kingdom! We're a cozy **18+ furry community**, and these rules keep it that way.\n\n**They apply everywhere:** every channel, voice chats, threads, the bots, the website, **Social**, and **your DMs with members you met here**. Read them all. By staying in the server, you agree to them.\n\nStaff use their judgement: something that isn't written down can still get you punished if it harms the community, and \"it wasn't in the rules\" isn't a loophole. Discord's [Terms of Service](https://discord.com/terms) and [Community Guidelines](https://discord.com/guidelines) apply too.",
  "tldr": [
    "Be kind. No hate, harassment or drama.",
    "18+ only. Lying about your age is a permanent ban.",
    "SFW channels stay SFW, and that includes dating talk.",
    "**Looking for a partner? Use Social, not the chat.** It needs 18+ Verified.",
    "**Ask before you DM.** No DM spam, no unsolicited NSFW, and no means no.",
    "No spam, ads, scams or begging.",
    "Respect people's privacy and boundaries.",
    "Listen to staff. Disagree through a ticket or an appeal."
  ],
  "parts": [
    {
      "key": "basics",
      "title": "The Basics",
      "label": "Part 1",
      "emoji": "🌿",
      "color": "#e87c2d",
      "intro": "",
      "rules": [
        {
          "n": 1,
          "title": "Be kind and respectful",
          "points": [
            "Treat everyone the way you'd want to be treated. Joking around is fine, but stop the moment someone isn't laughing.",
            "**No** harassment, bullying, threats, insults or targeting someone.",
            "**No** hate speech, slurs or discrimination based on race, ethnicity, gender, gender identity, sexuality, religion, disability, body or anything else people are.",
            "Don't start or bring drama, including drama from other servers. If an argument heats up, drop it or take it to a ticket."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 2,
          "title": "18+ only, and honest about it",
          "points": [
            "You must be **18 or older** to be here. No exceptions.",
            "Lying about your age, on your join form or anywhere else, or faking ID, is an **instant, permanent ban**.",
            "Don't joke or roleplay about being a minor, and don't post content that makes people look underage.",
            "Think someone is underage? Don't call them out in chat. Open a ticket in the support ticket channel and staff will handle it quietly."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 3,
          "title": "Follow Discord's rules",
          "points": [
            "Everything in Discord's Terms of Service and Community Guidelines applies here.",
            "Anything illegal is banned, in every channel, without exception."
          ],
          "bad": [],
          "good": []
        }
      ],
      "info": []
    },
    {
      "key": "chat",
      "title": "Chat & Channels",
      "label": "Part 2",
      "emoji": "💬",
      "color": "#ffc457",
      "intro": "",
      "rules": [
        {
          "n": 4,
          "title": "Keep SFW channels safe for work",
          "points": [
            "SFW channels mean **no** sexual talk, sexual jokes, kink talk or suggestive pictures, GIFs, emoji or stickers.",
            "Don't hint at NSFW, or bring it over from the 18+ channels. If you have to ask whether something's okay, take it to an NSFW channel (or don't post it).",
            "The same goes for voice: only voice chats labeled **NSFW** (like **NSFW VC #1** and **NSFW VC #2**) can be NSFW.",
            "Relationship and dating requests count too: see **Rule 9**."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 5,
          "title": "Use the right channel",
          "points": [
            "Keep each channel on its topic, and read the channel description before you post.",
            "Bot commands go in #bot-commands (unless a channel is meant for that bot, like games or bumping).",
            "Pictures, GIFs and reactions unlock with Media Perms at level 5. Post media in the media channels."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 6,
          "title": "No spam",
          "points": [
            "No message flooding, copy-paste walls, chain messages, or splitting one message into many lines.",
            "No caps, emoji, sticker or GIF spam.",
            "Don't mass ping, ping staff or roles without a real reason, or ghost ping.",
            "AutoMod catches most of this automatically: each catch is a strike, and strikes add up to mutes."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 7,
          "title": "No advertising or self-promotion",
          "points": [
            "No server invites, social media plugs, commission ads, selling or links to your stuff unless staff have said yes.",
            "That includes **DMing members** with ads or invites."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 8,
          "title": "Appropriate names and profiles",
          "points": [
            "Your name, nickname, avatar, banner, bio and status must be SFW, readable and not offensive.",
            "Don't impersonate staff, other members, bots or famous people.",
            "Staff can change your nickname, or ask you to change your profile, if it breaks these rules."
          ],
          "bad": [],
          "good": []
        }
      ],
      "info": []
    },
    {
      "key": "dating",
      "title": "Dating, Flirting & DMs",
      "label": "Part 3",
      "emoji": "💞",
      "color": "#ff73b3",
      "intro": "Lots of people come here to make friends, and some come to find more. That's welcome, as long as it happens in the right place and everyone stays comfortable.",
      "rules": [
        {
          "n": 9,
          "title": "Looking for a partner? Use Social, not the chat",
          "points": [
            "**Don't** post dating requests or advertise your relationship status in chat. That includes \"single and looking for a bf/gf\", \"who wants to date me?\", \"anyone single?\" and listing your age, sexuality or what you're looking for.",
            "Dating and partner-hunting happen on **[Social](https://www.kittykingdom.net/social)** on the website, where people choose to see it.",
            "**Dating is only for 18+ Verified members.** You get it by verifying your ID in the NSFW verification channel. If you aren't ID verified, you can't look for a partner anywhere in Kitty Kingdom.",
            "Being single, or talking about your partner, is fine. Advertising yourself is what isn't allowed."
          ],
          "bad": [
            "\"Hi! I'm 18 and single, looking for a gf 🥺\" (in general chat)",
            "\"Any cute boys wanna date? DM me\"",
            "\"Who's single here? 👀\""
          ],
          "good": [
            "Making a Social profile once you have 18+ Verified",
            "\"My partner and I watched a great movie last night\"",
            "Getting to know people by just chatting, as friends first"
          ]
        },
        {
          "n": 10,
          "title": "Flirting stays light, mutual and SFW",
          "points": [
            "Light, friendly flirting is okay **only if both people are clearly into it**, and in SFW channels it stays SFW.",
            "If someone ignores it, changes the subject or says stop, **stop**. Don't flirt with someone who's just being friendly.",
            "Don't flirt with or hit on new members who are just saying hello."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 11,
          "title": "Ask before you DM",
          "points": [
            "**Ask in chat before you DM someone** (\"mind if I DM you?\"). If they say no, or don't answer, that's a no.",
            "Respect DM status roles and anything in someone's bio that says DMs are closed.",
            "**No DM spam**: don't DM lots of members, mass message newcomers, or keep sending messages to someone who isn't replying. Send one message, then wait.",
            "**Never** send unsolicited NSFW content, pictures or sexual messages. Even with the NSFW role, ask first.",
            "DMs with members you met here count as part of the server. Report a rule-breaking DM to staff with screenshots, and they'll act on it."
          ],
          "bad": [
            "DMing 10 new members \"hey cutie 😏\"",
            "Sending a second, third and fourth message when someone hasn't replied",
            "Sending NSFW to someone who never asked for it"
          ],
          "good": [
            "\"Hey, loved your art! Mind if I DM you about it?\"",
            "Taking \"no thanks\" (or silence) as an answer"
          ]
        },
        {
          "n": 12,
          "title": "Consent and boundaries",
          "points": [
            "**No means no**, and so does \"not right now\" and \"I'm not comfortable with that\". Don't argue, guilt-trip or keep pushing.",
            "Don't ask for nudes, pictures, face reveals, addresses, phone numbers or other personal details.",
            "If someone blocks you, it's over. Don't contact them with alts, other apps or through friends.",
            "Pressuring, stalking or obsessing over a member is harassment, and is treated as such."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 13,
          "title": "Be honest and stay safe",
          "points": [
            "Be honest on your Social profile and with people you talk to. No catfishing: only post photos of yourself, and only art you own or have permission to use (credit the artist).",
            "Don't use Social or DMs to scam, advertise or collect people's personal information.",
            "Don't share someone's private messages, pictures or profile details without their permission (except to staff, for a report).",
            "Staff check age, nothing more. Be careful who you trust, take your time, and tell staff if anything feels wrong."
          ],
          "bad": [],
          "good": []
        }
      ],
      "info": []
    },
    {
      "key": "nsfw",
      "title": "The 18+ Area",
      "label": "Part 4",
      "emoji": "🥀",
      "color": "#9b59b6",
      "intro": "The NSFW side of Kitty Kingdom is for adults who've verified their age. Everything in Parts 1 to 3 still applies here, plus these.",
      "rules": [
        {
          "n": 14,
          "title": "Access: 18+ Verified only",
          "points": [
            "The NSFW channels, NSFW roles and NSFW voice chats need 18+ Verified. Get it by verifying your ID in the NSFW verification channel.",
            "NSFW content and talk only go in channels and voice chats **labeled NSFW**. Everywhere else is SFW.",
            "Never show, send, describe or screenshot NSFW content for members who aren't 18+ Verified, including in DMs.",
            "Faking verification, or helping someone underage get in, is a permanent ban for everyone involved."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 15,
          "title": "Never allowed: zero tolerance",
          "points": [
            "These are **instant permanent bans, anywhere on the server**: NSFW channels, voice chats, DMs, Social and profiles. Where the law or Discord requires it, they're also reported.",
            "**Minors:** anything sexual involving minors, or characters who look, act or are described as under 18. That includes \"cub\" content, sexual age-play and \"they're really 1,000 years old\" excuses.",
            "**Bestiality / zoophilia:** sexual content involving real animals, or real animals in a sexual context.",
            "**Non-consensual real content:** revenge porn, leaked or stolen nudes, hidden-camera content, and AI or edited nudes of real people.",
            "**Real harm:** real sexual violence, necrophilia, snuff, real gore, and animal cruelty."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 16,
          "title": "No illegal or stolen content",
          "points": [
            "Nothing illegal, anywhere: no selling or arranging drugs, weapons or other illegal goods and services, and no hacking, cheats or doxxing tools.",
            "**No pirated or leaked paid content:** artists' paywalled Patreon, Fansly or OnlyFans posts, commissions, or anything shared without the creator's permission.",
            "Don't post someone else's art or photos as your own. Credit artists, and remove a post if the artist asks."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 17,
          "title": "NSFW channel etiquette",
          "points": [
            "Keep each NSFW channel to its topic (art, real-life, roleplay and so on). Read the channel description first.",
            "**Real-life explicit content:** only of yourself, only if you're 18+, and only in channels meant for real-life content. Never post anyone else's.",
            "Put **extreme or niche kinks behind a spoiler tag** with a short content warning, like `||CW: kink name||`.",
            "Don't kink-shame. If something isn't for you, scroll past. If you think it breaks the rules, report it.",
            "Think about your own safety: crop out your face, tattoos and anything that shows where you live unless you're sure."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 18,
          "title": "Consent in the 18+ area",
          "points": [
            "Having the NSFW role **isn't consent**. Ask before you DM, and never send NSFW nobody asked for (see Rule 11).",
            "Roleplay and lewd chat need everyone involved to agree. If someone wants to stop, stop.",
            "**NSFW voice chats** (labeled NSFW, like **NSFW VC #1** and **NSFW VC #2**): NSFW talk is fine, but only show explicit content on camera or stream if **everyone** in the call is okay with it. The banned content above applies in voice too.",
            "Never record, screenshot or share someone's NSFW content, cam or voice without their permission (except privately to staff, to report a rule break)."
          ],
          "bad": [],
          "good": []
        }
      ],
      "info": []
    },
    {
      "key": "safety",
      "title": "Safety, Privacy & Fair Play",
      "label": "Part 5",
      "emoji": "🛡️",
      "color": "#5865f2",
      "intro": "",
      "rules": [
        {
          "n": 19,
          "title": "Privacy, Safety & Off-Server Conduct",
          "points": [
            "Don't share anyone's personal information (real name, address, photos, socials) or private messages without permission.",
            "**No doxxing, threats or intimidation.**",
            "Harassment or conflict connected to this server can be acted on, even when it happens outside Discord."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 20,
          "title": "No scams, dangerous links or begging",
          "points": [
            "No phishing, scams, fake giveaways, \"free Nitro\" links, malware or IP grabbers. Your account will be banned even if it was hacked. Secure it and appeal.",
            "Don't beg for Leaves, items, Nitro, money or gifts.",
            "Leaves and items are just for fun: **no buying or selling them for real money**."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 21,
          "title": "Play fair",
          "points": [
            "One account per person. Using alts to dodge a punishment, farm rewards or get around a block is a ban for every account.",
            "Don't exploit bugs, macros or self-bots to farm Leaves or XP. Found a bug? Report it in a ticket. That's how you stay in good standing (and you might get thanked for it)."
          ],
          "bad": [],
          "good": []
        },
        {
          "n": 22,
          "title": "Look after each other",
          "points": [
            "Heavy topics like self-harm, abuse or mental health crises are okay to mention, but be gentle, and don't post graphic details.",
            "Staff and members aren't professionals. If you or someone else is in danger, contact local emergency services or a crisis line.",
            "Worried about someone? Tell staff in a ticket."
          ],
          "bad": [],
          "good": []
        }
      ],
      "info": []
    },
    {
      "key": "voice",
      "title": "Voice Chats",
      "label": "Part 6",
      "emoji": "🎙️",
      "color": "#2ecc71",
      "intro": "",
      "rules": [
        {
          "n": 23,
          "title": "Voice chat rules",
          "points": [
            "To join voice chats, sign the **Voice Channel Terms** to get VC. Every rule above applies in voice too.",
            "Voice chats are **SFW**, including what's on your stream or camera, **except** the ones labeled NSFW (like **NSFW VC #1** and **NSFW VC #2**), which are for 18+ Verified members. See **Rule 18**.",
            "**No** ear-rape, loud noises, soundboard or music spam, or voice changers used to annoy people.",
            "**Never record** a voice chat or stream without everyone's permission. The one exception: a short clip sent **privately to staff** to report a rule break.",
            "Muted or deafened for 5 minutes? You'll be moved to AFK. That's normal, and not a punishment."
          ],
          "bad": [],
          "good": []
        }
      ],
      "info": []
    },
    {
      "key": "staff",
      "title": "Staff, Reports & Punishments",
      "label": "Part 7",
      "emoji": "⚖️",
      "color": "#e5484d",
      "intro": "",
      "rules": [
        {
          "n": 24,
          "title": "Respect staff decisions",
          "points": [
            "Follow staff instructions. If you disagree, open a ticket or an appeal, calmly. Don't argue about it in chat.",
            "Don't mini-mod (tell people off yourself). Report it, and let staff handle it.",
            "Never pretend to be staff, or lie to staff in reports or appeals."
          ],
          "bad": [],
          "good": []
        }
      ],
      "info": [
        {
          "title": "🚨 How to report something",
          "body": "Open a ticket in the support ticket channel. Include **screenshots or message links** and who was involved. Reports are private: the person won't know who reported them."
        },
        {
          "title": "📈 How punishments work",
          "body": "Most rule breaks go **warning → mute → longer mute → ban**, depending on how serious it is and your history.\nSerious ones can skip straight to a **ban**: lying about age, anything involving minors, doxxing, threats, scams, raids and mass DM spam.\n**AutoMod** removes slurs, spam, scam links and invites by itself. Its strikes add up to timed mutes."
        },
        {
          "title": "📋 Your record and appeals",
          "body": "Type `/punishments` to see your record. Think a punishment was wrong? Appeal at **[kittykingdom.net/appeals](https://www.kittykingdom.net/appeals)**. Banned members are emailed how to appeal."
        },
        {
          "title": "🔄 Rule changes",
          "body": "These rules can be updated at any time, and changes are announced. Not knowing a rule doesn't excuse breaking it."
        }
      ]
    }
  ]
};
