// The topics on the stats page's topic map. The word lists must match main_bot/db/topic_words.py,
// which is what the bot counts (only these words are ever counted, never whole messages).

export const TOPICS: Record<string, { label: string; color: string; icon: string; words: string[] }> = {
  gaming: { label: "Gaming", color: "#8b5cf6", icon: "Gamepad2", words: ["game", "games", "gaming", "gamer", "minecraft", "fortnite", "valorant", "roblox", "steam", "xbox", "playstation", "ps5", "switch", "nintendo", "pokemon", "zelda", "overwatch", "league", "apex", "cod", "gta", "elden", "rpg", "fps", "mmo", "speedrun", "lobby", "queue", "ranked", "controller", "console", "pc", "boss", "loot", "respawn", "multiplayer", "coop", "terraria", "stardew", "genshin", "hollow"] },
  music: { label: "Music", color: "#ec4899", icon: "Music", words: ["music", "song", "songs", "album", "band", "singer", "spotify", "playlist", "concert", "guitar", "piano", "drums", "rap", "rock", "pop", "edm", "lyrics", "beat", "vinyl", "headphones", "sing", "singing", "karaoke", "dj", "remix", "tune", "melody"] },
  anime: { label: "Anime & manga", color: "#f43f5e", icon: "Sparkles", words: ["anime", "manga", "waifu", "husbando", "otaku", "naruto", "onepiece", "jjk", "demonslayer", "aot", "ghibli", "crunchyroll", "cosplay", "weeb", "kawaii", "senpai", "chan", "kun", "shonen", "isekai", "mha"] },
  shows: { label: "Movies & TV", color: "#6366f1", icon: "Clapperboard", words: ["movie", "movies", "film", "films", "netflix", "hulu", "disney", "marvel", "show", "shows", "series", "episode", "season", "trailer", "cinema", "theater", "binge", "watching", "documentary", "cartoon", "sitcom"] },
  art: { label: "Art & creating", color: "#f59e0b", icon: "Palette", words: ["art", "drawing", "draw", "sketch", "paint", "painting", "artist", "commission", "commissions", "doodle", "digital", "procreate", "canvas", "design", "photo", "photography", "craft", "crafts", "sewing", "knitting", "sculpt", "animation", "oc", "character", "ref"] },
  furry: { label: "Furry life", color: "#f97316", icon: "PawPrint", words: ["furry", "furries", "fursona", "fursuit", "fursuits", "fluff", "fluffy", "tail", "tails", "paws", "paw", "ears", "floof", "scalie", "protogen", "sergal", "wolf", "fox", "dragon", "cat", "yiff", "furcon", "suiting", "species", "uwu", "owo"] },
  pets: { label: "Pets & animals", color: "#84cc16", icon: "Dog", words: ["pet", "pets", "dog", "dogs", "puppy", "pupper", "kitten", "kitty", "cats", "hamster", "bunny", "rabbit", "bird", "parrot", "fish", "snake", "lizard", "vet", "walkies", "adopted", "rescue"] },
  food: { label: "Food & drink", color: "#ef4444", icon: "Pizza", words: ["food", "eat", "eating", "hungry", "dinner", "lunch", "breakfast", "snack", "snacks", "pizza", "burger", "tacos", "sushi", "ramen", "pasta", "chocolate", "coffee", "tea", "boba", "cake", "cookies", "cook", "cooking", "bake", "baking", "recipe", "drink", "soda", "chips", "fries", "icecream", "candy"] },
  tech: { label: "Tech & code", color: "#0ea5e9", icon: "Cpu", words: ["code", "coding", "program", "programming", "python", "javascript", "discord", "bot", "server", "website", "computer", "laptop", "phone", "iphone", "android", "linux", "windows", "mac", "wifi", "internet", "ai", "chatgpt", "gpu", "cpu", "build", "bug", "update", "app", "keyboard", "mouse", "monitor"] },
  sports: { label: "Sports & fitness", color: "#22c55e", icon: "Dumbbell", words: ["sport", "sports", "gym", "workout", "football", "soccer", "basketball", "baseball", "hockey", "nfl", "nba", "run", "running", "hike", "hiking", "swim", "swimming", "bike", "biking", "skate", "yoga", "lift", "lifting", "team", "match", "score"] },
  school: { label: "School & work", color: "#64748b", icon: "Briefcase", words: ["school", "class", "classes", "homework", "exam", "exams", "test", "teacher", "college", "university", "uni", "study", "studying", "grades", "work", "job", "boss", "shift", "coworker", "office", "meeting", "interview", "hired", "paycheck"] },
  memes: { label: "Memes & jokes", color: "#facc15", icon: "Laugh", words: ["meme", "memes", "lol", "lmao", "lmfao", "rofl", "haha", "hahaha", "xd", "bruh", "sus", "based", "cringe", "ratio", "skull", "funny", "joke", "jokes", "shitpost", "copium", "yeet", "pog", "poggers"] },
  feelings: { label: "Feelings & support", color: "#e879f9", icon: "HeartHandshake", words: ["happy", "sad", "love", "lonely", "tired", "stressed", "anxious", "anxiety", "depressed", "excited", "angry", "mad", "upset", "hurt", "cry", "crying", "hug", "hugs", "vent", "venting", "feel", "feeling", "feelings", "support", "proud", "grateful", "thankful", "miss"] },
  dating: { label: "Love & dating", color: "#fb7185", icon: "Heart", words: ["date", "dating", "crush", "boyfriend", "girlfriend", "partner", "bf", "gf", "relationship", "single", "cute", "kiss", "flirt", "flirting", "romance", "romantic", "valentine", "married", "wife", "husband", "ex", "breakup", "cuddle", "cuddles"] },
  chill: { label: "Sleep & chilling", color: "#818cf8", icon: "Moon", words: ["sleep", "sleepy", "nap", "bed", "tired", "chill", "chilling", "relax", "relaxing", "vibe", "vibes", "vibing", "lazy", "weekend", "night", "morning", "goodnight", "gn", "gm", "morning", "awake", "insomnia"] },
  weather: { label: "Seasons & holidays", color: "#38bdf8", icon: "CloudSun", words: ["weather", "rain", "raining", "snow", "snowing", "storm", "sunny", "hot", "cold", "freezing", "summer", "winter", "spring", "autumn", "fall", "halloween", "christmas", "holiday", "holidays", "birthday", "bday", "party", "thanksgiving", "newyear"] },
  travel: { label: "Travel & places", color: "#14b8a6", icon: "Plane", words: ["travel", "trip", "vacation", "flight", "plane", "airport", "beach", "ocean", "mountains", "camping", "roadtrip", "hotel", "visit", "visiting", "abroad", "europe", "japan", "city", "drive", "driving", "car"] },
  books: { label: "Books & writing", color: "#a16207", icon: "BookOpen", words: ["book", "books", "read", "reading", "novel", "author", "story", "stories", "writing", "write", "poem", "poetry", "fanfic", "library", "chapter", "fantasy", "scifi", "lore", "worldbuilding"] },
  leaves: { label: "Leaves & the server", color: "#65a30d", icon: "Leaf", words: ["leaves", "leaf", "store", "shop", "buy", "bought", "daily", "slots", "gamble", "gambling", "booster", "boost", "level", "levels", "xp", "rank", "leaderboard", "bump", "rich", "broke", "coins"] },
};
