// The topics on the stats page's topic map. Generated from main_bot/db/topic_ai.py (the bot's topic AI):
// keep the keys and keyword lists in sync with it.

export const TOPIC_GROUPS: Record<string, { label: string }> = {
  games: { label: "Games" },
  entertainment: { label: "Entertainment" },
  creative: { label: "Creative" },
  community: { label: "Community" },
  social: { label: "Social" },
  life: { label: "Life" },
  mind: { label: "Tech & mind" },
  nsfw: { label: "18+" },
};

export const TOPICS: Record<string, { label: string; group: string; color: string; icon: string; words: string[] }> = {
  gaming: { label: "Gaming", group: "games", color: "#3840d0", icon: "Gamepad2", words: ["game", "games", "gaming", "gamer", "lobby", "queue", "ranked", "controller", "console", "loot", "respawn", "multiplayer", "coop", "steam", "xbox", "playstation", "ps5"] },
  sandbox: { label: "Minecraft & sandbox", group: "games", color: "#4038d0", icon: "Pickaxe", words: ["minecraft", "terraria", "roblox", "creeper", "redstone", "sandbox", "modpack", "mods", "crafting"] },
  shooters: { label: "Shooters & competitive", group: "games", color: "#5038d0", icon: "Crosshair", words: ["valorant", "fortnite", "apex", "cod", "overwatch", "csgo", "cs2", "shooter", "fps", "headshot", "clutch", "battlepass", "rivals"] },
  rpg: { label: "RPGs & adventure", group: "games", color: "#6038d0", icon: "Swords", words: ["rpg", "elden", "skyrim", "zelda", "quest", "dungeon", "grind", "bg3", "genshin", "souls", "mmo", "wow"] },
  cozy: { label: "Cozy games", group: "games", color: "#7038d0", icon: "Sprout", words: ["stardew", "cozy", "farming", "sims", "simulator", "animalcrossing"] },
  nintendo: { label: "Nintendo & Pok\u00e9mon", group: "games", color: "#7f38d0", icon: "Gamepad", words: ["pokemon", "nintendo", "mario", "kirby", "smash", "pikachu", "shiny", "eevee"] },
  tabletop: { label: "Tabletop & cards", group: "games", color: "#8f38d0", icon: "Dices", words: ["dnd", "campaign", "dice", "boardgame", "mtg", "tabletop", "deck", "d20"] },
  vr: { label: "VR & VRChat", group: "games", color: "#9f38d0", icon: "Glasses", words: ["vr", "vrchat", "vrc", "headset", "fbt", "avatar"] },
  horror: { label: "Horror & spooky", group: "games", color: "#af38d0", icon: "Ghost", words: ["horror", "scary", "creepy", "spooky", "jumpscare", "ghost", "haunted", "fnaf", "dbd"] },
  music: { label: "Music", group: "entertainment", color: "#bc38d0", icon: "Music", words: ["music", "song", "songs", "album", "band", "singer", "spotify", "playlist", "concert", "lyrics", "vinyl", "rap", "rock", "edm"] },
  kpop: { label: "K-pop & idols", group: "entertainment", color: "#cd38d0", icon: "Mic2", words: ["kpop", "bts", "blackpink", "idol", "idols", "stan", "twice", "stray"] },
  anime: { label: "Anime & manga", group: "entertainment", color: "#d038c1", icon: "Sparkles", words: ["anime", "manga", "waifu", "husbando", "otaku", "naruto", "jjk", "aot", "ghibli", "crunchyroll", "weeb", "isekai", "mha"] },
  movies: { label: "Movies & TV", group: "entertainment", color: "#d038af", icon: "Clapperboard", words: ["movie", "movies", "film", "netflix", "hulu", "disney", "series", "episode", "trailer", "cinema", "binge", "documentary", "cartoon"] },
  comics: { label: "Comics & superheroes", group: "entertainment", color: "#d0389d", icon: "Zap", words: ["marvel", "dc", "batman", "spiderman", "superhero", "comics", "avengers", "deadpool"] },
  creators: { label: "YouTube & streamers", group: "entertainment", color: "#d0388c", icon: "MonitorPlay", words: ["youtube", "youtuber", "twitch", "stream", "streamer", "tiktok", "vod", "clip", "subscribers", "vtuber"] },
  memes: { label: "Memes & jokes", group: "entertainment", color: "#d0387a", icon: "Laugh", words: ["meme", "memes", "lol", "lmao", "lmfao", "rofl", "haha", "xd", "bruh", "sus", "based", "cringe", "ratio", "skull", "joke", "shitpost", "yeet", "pog"] },
  books: { label: "Books & writing", group: "entertainment", color: "#d03868", icon: "BookOpen", words: ["book", "books", "reading", "novel", "author", "story", "writing", "poem", "poetry", "fanfic", "chapter", "lore", "worldbuilding"] },
  art: { label: "Art & drawing", group: "creative", color: "#d04a38", icon: "Palette", words: ["art", "drawing", "draw", "sketch", "paint", "painting", "artist", "commission", "commissions", "doodle", "procreate", "oc", "ref", "animation"] },
  photos: { label: "Photos & selfies", group: "creative", color: "#d06638", icon: "Camera", words: ["photo", "pic", "pics", "selfie", "selfies", "camera", "photography", "lens"] },
  crafts: { label: "Crafts & DIY", group: "creative", color: "#d08338", icon: "Scissors", words: ["craft", "crafts", "diy", "sewing", "knitting", "crochet", "beads", "3dprint", "resin"] },
  makingmusic: { label: "Making music", group: "creative", color: "#d09f38", icon: "Guitar", words: ["guitar", "piano", "drums", "bass", "producing", "beat", "daw", "fl", "singing", "karaoke", "cover"] },
  fashion: { label: "Fashion & style", group: "creative", color: "#d0bb38", icon: "Shirt", words: ["outfit", "fashion", "clothes", "hoodie", "shoes", "makeup", "nails", "hair", "cosplay", "drip", "piercing", "tattoo"] },
  furry: { label: "Furry life", group: "community", color: "#d03840", icon: "PawPrint", words: ["furry", "furries", "fursona", "fursuit", "fursuits", "floof", "fluffy", "tail", "paws", "scalie", "protogen", "sergal", "furcon", "uwu", "owo", "awoo", "mrrp", "nya"] },
  server: { label: "The server", group: "community", color: "#d05438", icon: "Castle", words: ["server", "staff", "mod", "mods", "admin", "channel", "role", "roles", "ticket", "discord", "ping", "announcement"] },
  leaves: { label: "Leaves & economy", group: "community", color: "#d07738", icon: "Leaf", words: ["leaves", "leaf", "store", "shop", "daily", "slots", "gamble", "booster", "level", "xp", "rank", "leaderboard", "bump"] },
  greetings: { label: "Hellos & goodbyes", group: "community", color: "#d09b38", icon: "Hand", words: ["hi", "hello", "hey", "heya", "hiya", "morning", "gm", "gn", "goodnight", "welcome", "bye", "cya", "wb"] },
  feelings: { label: "Feelings & support", group: "social", color: "#d038b2", icon: "HeartHandshake", words: ["happy", "sad", "lonely", "tired", "stressed", "excited", "angry", "upset", "hurt", "cry", "crying", "hug", "hugs", "vent", "feel", "feelings", "support", "grateful", "miss"] },
  mentalhealth: { label: "Mental health", group: "social", color: "#d038a3", icon: "Brain", words: ["anxiety", "depression", "depressed", "therapy", "therapist", "meds", "panic", "burnout", "selfcare", "adhd", "autism", "autistic", "trauma"] },
  love: { label: "Love & dating", group: "social", color: "#d03895", icon: "Heart", words: ["date", "dating", "crush", "boyfriend", "girlfriend", "partner", "bf", "gf", "relationship", "kiss", "romance", "married", "wife", "husband", "breakup", "cuddle", "cuddles"] },
  friends: { label: "Friends & hangouts", group: "social", color: "#d03887", icon: "Users", words: ["friend", "friends", "bestie", "bff", "hangout", "squad", "homie", "buddy", "pals"] },
  drama: { label: "Drama & gossip", group: "social", color: "#d03879", icon: "Flame", words: ["drama", "tea", "gossip", "beef", "argument", "fight", "toxic", "rude", "blocked", "petty"] },
  hype: { label: "Compliments & hype", group: "social", color: "#d0386b", icon: "PartyPopper", words: ["cute", "pretty", "handsome", "gorgeous", "amazing", "awesome", "proud", "congrats", "gg", "slay", "queen", "king", "legend", "icon"] },
  pride: { label: "Identity & pride", group: "social", color: "#d0385d", icon: "Rainbow", words: ["lgbt", "lgbtq", "gay", "lesbian", "bi", "bisexual", "trans", "nonbinary", "enby", "pride", "pronouns", "queer"] },
  family: { label: "Family & home", group: "social", color: "#d0384e", icon: "Home", words: ["mom", "dad", "mum", "sister", "brother", "sibling", "family", "parents", "grandma", "grandpa", "cousin", "aunt", "uncle"] },
  advice: { label: "Questions & advice", group: "social", color: "#d03840", icon: "HelpCircle", words: ["advice", "help", "question", "recommend", "recommendation", "tips", "suggest", "opinion"] },
  rants: { label: "Rants & complaints", group: "social", color: "#d03e38", icon: "Angry", words: ["annoying", "hate", "ugh", "rant", "stupid", "worst", "sucks", "mad", "pissed"] },
  school: { label: "School & studying", group: "life", color: "#38d03d", icon: "GraduationCap", words: ["school", "class", "classes", "homework", "exam", "exams", "test", "teacher", "college", "university", "uni", "study", "studying", "grades", "essay"] },
  work: { label: "Work & jobs", group: "life", color: "#38d045", icon: "Briefcase", words: ["work", "job", "boss", "shift", "coworker", "coworkers", "office", "meeting", "interview", "hired", "fired", "paycheck", "overtime"] },
  money: { label: "Money & shopping", group: "life", color: "#38d04d", icon: "Wallet", words: ["money", "cash", "bills", "rent", "expensive", "cheap", "sale", "amazon", "order", "bought", "shopping", "paycheck"] },
  sleep: { label: "Sleep & tiredness", group: "life", color: "#38d055", icon: "Moon", words: ["sleep", "sleepy", "nap", "bed", "bedtime", "insomnia", "awake", "exhausted", "zzz"] },
  chill: { label: "Chilling & vibes", group: "life", color: "#38d05d", icon: "Coffee", words: ["chill", "chilling", "relax", "relaxing", "vibe", "vibes", "vibing", "lazy"] },
  health: { label: "Health & sick days", group: "life", color: "#38d065", icon: "Thermometer", words: ["sick", "ill", "doctor", "hospital", "headache", "fever", "covid", "pain", "injury", "surgery", "dentist"] },
  fitness: { label: "Fitness & gym", group: "life", color: "#38d06c", icon: "Dumbbell", words: ["gym", "workout", "lift", "lifting", "gains", "run", "running", "cardio", "yoga", "protein", "diet"] },
  sports: { label: "Sports", group: "life", color: "#38d074", icon: "Trophy", words: ["sport", "sports", "football", "soccer", "basketball", "baseball", "hockey", "nfl", "nba", "f1", "wrestling", "ufc"] },
  food: { label: "Food & cooking", group: "life", color: "#38d07c", icon: "Pizza", words: ["food", "eat", "eating", "hungry", "dinner", "lunch", "breakfast", "snack", "pizza", "burger", "tacos", "sushi", "ramen", "pasta", "chocolate", "cake", "cook", "cooking", "bake", "baking", "recipe", "fries"] },
  drinks: { label: "Coffee & drinks", group: "life", color: "#38d084", icon: "CupSoda", words: ["coffee", "tea", "boba", "soda", "monster", "redbull", "energy", "latte", "matcha", "juice"] },
  partying: { label: "Drinking & parties", group: "life", color: "#38d08c", icon: "Wine", words: ["beer", "wine", "vodka", "drunk", "tipsy", "shots", "party", "club", "bar", "hangover", "alcohol"] },
  smoking: { label: "420 & smoking", group: "life", color: "#38d094", icon: "Cigarette", words: ["weed", "420", "stoned", "blunt", "joint", "vape", "smoke", "edible", "edibles", "bong", "cannabis"] },
  weather: { label: "Weather & seasons", group: "life", color: "#38d09c", icon: "CloudSun", words: ["weather", "rain", "raining", "snow", "snowing", "storm", "sunny", "cold", "freezing", "summer", "winter", "spring", "autumn"] },
  holidays: { label: "Holidays & birthdays", group: "life", color: "#38d0a4", icon: "Gift", words: ["birthday", "bday", "christmas", "halloween", "thanksgiving", "easter", "holiday", "holidays", "presents", "gifts", "newyear"] },
  travel: { label: "Travel & places", group: "life", color: "#38d0ab", icon: "Plane", words: ["travel", "trip", "vacation", "flight", "plane", "airport", "hotel", "visit", "abroad", "europe", "japan", "roadtrip"] },
  cars: { label: "Cars & driving", group: "life", color: "#38d0b3", icon: "Car", words: ["car", "cars", "drive", "driving", "truck", "license", "engine", "jdm", "racing", "tesla", "motorcycle"] },
  nature: { label: "Nature & outdoors", group: "life", color: "#38d0bb", icon: "Trees", words: ["nature", "forest", "trees", "camping", "hiking", "hike", "flowers", "garden", "beach", "ocean", "lake", "mountains"] },
  pets: { label: "Pets & animals", group: "life", color: "#38d0c3", icon: "Dog", words: ["pet", "pets", "dog", "dogs", "puppy", "kitten", "cat", "cats", "hamster", "bunny", "bird", "fish", "snake", "lizard", "vet", "rescue"] },
  tech: { label: "Tech & gadgets", group: "mind", color: "#38d0bc", icon: "Cpu", words: ["computer", "laptop", "phone", "iphone", "android", "pc", "gpu", "cpu", "wifi", "internet", "keyboard", "mouse", "monitor", "headphones"] },
  coding: { label: "Coding & bots", group: "mind", color: "#38d0cd", icon: "Code2", words: ["code", "coding", "program", "programming", "python", "javascript", "bot", "website", "bug", "github", "linux", "api", "server"] },
  ai: { label: "AI & chatbots", group: "mind", color: "#38c1d0", icon: "Bot", words: ["ai", "chatgpt", "gpt", "claude", "chatbot", "prompt", "generated", "llm"] },
  science: { label: "Science & space", group: "mind", color: "#38afd0", icon: "Rocket", words: ["space", "planet", "nasa", "science", "physics", "chemistry", "biology", "galaxy", "universe", "moon"] },
  news: { label: "News & politics", group: "mind", color: "#389dd0", icon: "Newspaper", words: ["politics", "election", "president", "government", "news", "vote", "war", "law", "policy"] },
  spiritual: { label: "Spirituality & astrology", group: "mind", color: "#388cd0", icon: "Star", words: ["zodiac", "astrology", "tarot", "crystals", "religion", "god", "church", "pray", "spiritual", "horoscope"] },
  languages: { label: "Languages & cultures", group: "mind", color: "#387ad0", icon: "Languages", words: ["language", "languages", "spanish", "french", "german", "japanese", "korean", "english", "duolingo", "translate"] },
  crypto: { label: "Crypto & investing", group: "mind", color: "#3868d0", icon: "Bitcoin", words: ["crypto", "bitcoin", "btc", "eth", "stocks", "invest", "investing", "nft", "trading"] },
  flirting: { label: "Flirting & thirst", group: "nsfw", color: "#d0388c", icon: "Flame", words: ["hot", "sexy", "thirsty", "thirst", "rizz", "flirt", "flirting", "daddy", "mommy"] },
  lewd: { label: "Lewd & horny", group: "nsfw", color: "#d0386f", icon: "EyeOff", words: ["nsfw", "lewd", "horny", "nudes", "spicy", "naughty", "freaky", "bonk"] },
  kinks: { label: "Kinks & fetishes", group: "nsfw", color: "#d03853", icon: "Lock", words: ["kink", "kinky", "kinks", "fetish", "bdsm", "collar", "leash", "bondage", "brat"] },
  furry18: { label: "Furry 18+", group: "nsfw", color: "#d03a38", icon: "PawPrint", words: ["yiff", "murr", "murrsuit", "e621", "knot"] },
  hookups: { label: "Hookups & sex", group: "nsfw", color: "#d05638", icon: "BedDouble", words: ["sex", "hookup", "hookups", "fwb", "nsfw", "smut"] },
};
