"""Generates lib/rules-data.ts (the website's Rules tab) from the moderation bot's db/rules_content.py.

    python3 scripts/gen-rules.py /path/to/Moderation/db/rules_content.py

Discord-only bits are adapted: channel and role tokens become plain names, and any point that shows the join
password is left out (the password is only in Discord's #rules).
"""

import importlib.util
import json
import re
import sys
from pathlib import Path

src = Path(sys.argv[1])
spec = importlib.util.spec_from_file_location("rules_content", src)
RC = importlib.util.module_from_spec(spec)
spec.loader.exec_module(RC)


def web(text: str) -> str:
    text = re.sub(r"\[\[ch:(\w+)\]\]", lambda m: RC.CHANNELS[m.group(1)][1], text)
    return re.sub(r"\[\[role:(\w+)\]\]", lambda m: RC.ROLES[m.group(1)][1], text)


parts = []
for part in RC.numbered_parts():
    parts.append({
        "key": part["key"],
        "title": part["title"].split(" · ", 1)[-1],
        "label": part["title"].split(" · ", 1)[0],
        "emoji": part["emoji"],
        "color": "#%02x%02x%02x" % tuple(part["color"]),
        "intro": web(part.get("intro", "")),
        "rules": [
            {
                "n": r["n"],
                "title": r["title"],
                "points": [web(p) for p in r["points"] if "{PASSWORD}" not in p],
                "bad": [web(x) for x in r.get("examples", {}).get("bad", [])],
                "good": [web(x) for x in r.get("examples", {}).get("good", [])],
            }
            for r in part["rules"]
        ],
        "info": [{"title": t, "body": web(b)} for t, b in part.get("info", [])],
    })

data = {"intro": web(RC.INTRO), "tldr": [web(t) for t in RC.TLDR], "parts": parts}
out = Path(__file__).resolve().parent.parent / "lib" / "rules-data.ts"
out.write_text(
    "// GENERATED by scripts/gen-rules.py from the moderation bot's db/rules_content.py. Don't edit by hand:\n"
    "// change the bot file, run the script, and run /rules refresh in Discord so both stay the same.\n"
    "// Text uses **bold** and [links](url).\n\n"
    "export type Rule = { n: number; title: string; points: string[]; bad: string[]; good: string[] };\n"
    "export type RulePart = { key: string; title: string; label: string; emoji: string; color: string; intro: string; rules: Rule[]; info: { title: string; body: string }[] };\n\n"
    f"export const RULES: {{ intro: string; tldr: string[]; parts: RulePart[] }} = {json.dumps(data, ensure_ascii=False, indent=2)};\n"
)
print(f"Wrote {out} ({sum(len(p['rules']) for p in parts)} rules)")
